name: health_one
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.2.1
  colorful_safe_area: ^1.0.0
  font_awesome_flutter: ^10.7.0
  dynamic_tabbar: ^1.0.8
  flutter_chat_ui: ^1.6.15
  uuid: ^4.5.1
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  material_symbols_icons: ^4.2789.0
  wheel_picker: ^0.1.1
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee.ttf
    - family: AfacadFlux
      fonts:
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Thin.ttf
          weight: 100
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Regular.ttf
          weight: 400
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Bold.ttf
          weight: 700
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Bold.ttf
          weight: 900

  assets:
    - .env
    - assets/svg/
    - assets/png/
    - assets/gif/
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/png/logo-color.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

